version: '3'
services:
  gcc_base:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        UID: 1000
        GID: 1000
        CMAKE_VERSION: 3.27.2
        USER_PASSWORD: user
        USER_NAME: user
        DEV_FOLDER: project
    environment:
      - TZ=Europe/Moscow

    volumes:
      - ./project:/home/user/project:cached

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    #Uncomment if used vscode
    # command: /bin/sh -c "while sleep 1000; do :; done"
    #Uncomment if usued other
    ports:
      - "2222:22"
    command: /root/run.sh
 
